version: "3"
services:
  # An old issue: docker-compose will mount volume as root.
  # Workaround: https://github.com/docker/compose/issues/3270
  # (Command 'docker run -v' is fine)
  file-chown:
    container_name: file-chown
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/sd-webui-base:nightly"
    user: "root"
    volumes: 
      - "../volume:/home/runner"
    command: "chown -R runner:runner /home/runner"
  stable-diffusion:
    container_name: sd-webui
    depends_on:
      file-chown:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/sd-webui-base:nightly"
    ports:
      - "7860:7860"
    volumes:
      - "../volume:/home/runner"
    environment:
      - CLI_ARGS=--xformers --medvram --allow-code --api --enable-insecure-extension-access 
    stop_signal: SIGINT
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
