name: Publish "nightly" to Docker Hub

on: 
  workflow_dispatch: # trigger manually
  schedule: # Runs on every (3,8,13,18,23,28) day-of-month, 07:00 UTC
    - cron: '0 7 3-31/5 * *'

jobs:

  build-publish:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - 
        name: Git checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./nightly
          file: ./nightly/Dockerfile
          tags: yanwk/sd-webui-base:nightly
          push: true
